---
title: JavaScript异步回调的两个问题——控制反转与执行栈隔离  
date: 2018-08-14
tags:
 - javascript        
categories: 
 - frontEnd
---

## 异步机制与回调

当JS解析到一个异步操作时，为避免**单线程阻塞**，会将异步推入**消息队列**中，等到**同步执行栈**清空，再将消息队列中异步操作依次取出来丢到同步执行栈中执行，同步执行栈清空的间隔也称为一次**事件循环**。消息队列分为**微任务**队列和**宏任务**队列，在一次事件循环开始时，微任务拥有执行优先权。

JS通过回调函数来承载异步会引发信任问题——**控制反转**，即封装一个异步API的时候往往传入回调作为异步后的处理，问题是无法信任一个异步的API的情况，报错与否，成功与否，如何执行传入的回调等。另一个回调函数来承载异步的问题是堆栈信息断开诱发的**回调地狱**，同步栈清空后，通过回调函数承载的异步才会开始，这导致执行异步堆栈信息丢失，可以通过传参来保证堆栈信息的衔接，但是不稳定，试想异步前的引用类型参数在异步后的同步操作更改引用类型的数值，结果可能与预期不一致。在异步继发时这个问题尤为明显，下一步的异步操作取决于上一份的异步结果，不仅需要考虑到回调顺序，错误捕捉和处理，还需确保参数的稳定。如下代码是常用的回调封装的ajax：

```js
function ajax(method, url, done, fail) {
    var xhr = new XMLHttpRequest();
    xhr.open(method, url);
    xhr.onload = function (e) {
        if (this.status < 300)	typeof done == "function" && done(this.response, e);
        else  typeof fail == "function" && fail(e);
    };
    xhr.onabort = xhr.onerror = xhr.ontimeout = fail;
    xhr.send(JSON.stringify(args));
    return xhr;
}
```

## Promise

Promise有效的解决了控制反转问题，控制反转其本质是无法信任的API内部的回调会被如何对待，是一种被动的接受异步状态，但如果能够把控制反转再反转回来，也称之为Promise范式，希望无法信任的API只需给予一个异步的结果，那么代码将变得主动接管，而且对于长时间的未决状态可以设置延时阻断。那么问题是是否可信任反转后的结果？`Promise`中有三种状态，只有异步操作的结果决定当前是哪一种状态，任何操作都无法改变，而且一旦状态发生改变就不会再次改变，适用于一次性事件（导致也`Promise`不适合多次触发的事件），这样保证了`Promise`反转后的结果是可信任的！如下是promise封装的ajax：

```js
function ajax(method, url){
	return new Promise((resolve,reject)={
		var xhr = new XMLHttpRequest();
    	xhr.open(method, url);
    	xhr.onload = function (e) {
            if (this.status < 300)	resolve(this.response)
            else  reject(e)
    	};
    	xhr.onabort = xhr.onerror = xhr.ontimeout = fail;
    	xhr.send(JSON.stringify(args));
	})
}
ajax(method, url).then((res)=>{
    return ajax(otherMethod,otherUrl)
}).then((res)=>{
    //do something
}).catch((e)=>{throw new Error('error'+e)})
```

promise另一个优点在于简洁的容错机制，回调地狱中的错误处理不容易判定哪里出现了错误，而且 `try catch` 语句也无法在异步条件下直接捕获错误，另外回调还需要对每一个错误都需要做预处理，导致传入的第一个参数必须是错误对象，因为其原来的上下文环境结束，无法捕捉错误，只能当参数传递。`Promise`中的链式调用一旦`reject`或者抛出错误那么直接到`catch`实例方法中统一处理，而不是手动传参或者冗杂的容错判断。


## Generator

在没有`Generator`之前，`Promise`看上去只是回调的包装器，其本质是将代码包裹成回调函数，由于异步，带来的弊端就是**脱离函数的执行上下文栈**，只能通过传参将有用的前一个结果传递给后一个结果。如果在一个函数中遇到异步暂停执行异步后的代码，而等到异步的结果再恢复执行，这样回调嵌套就会消失，代码也不分割，像写同步函数一样写异步函数。`Generator`正是基于这样的考虑，它和之前的异步处理方式有着根本性变革，保证了执行上下文环境。如下代码用`Generator`改造的`ajax`：

```js
function ajax(method, url){
	let xhr = new XMLHttpRequest();
    xhr.open(method, url);
    xhr.onload = function (e) {
        if (this.status < 300)	return this.response
        else  return e
    };
    xhr.onabort = xhr.onerror = xhr.ontimeout = fail;
    xhr.send(JSON.stringify(args));
}
function* gen(method, url){
    let res = yield ajax(method, url)
    let temRes = JSON.parse(res)
   	let otherRes = yield ajax(temRes)
    let temOtherRes = JSON.parse(res)
    return [temRes,temOtherRes]
}
var g = gen(method, url)
g.next()
g.next()
g.next()
```
Generator最大的问题就是再次获取执行权的问题，就像分布式事件类似，因为它返回的是一个遍历器对象，因此每次都需要手动获取，而不会在异步之后自动得到执行权。可以与回调或Promise结合获取自动执行权，**Thunk**函数和**co**模块正是以此来达到Generator的自动流程管理。而与Promise结合会融合两者共同的优点，如统一的错误处理，控制反转再反转，支持并发等。

## async & await

**async & await**内置自动执行器，而且async返回一个Promise，它取决于await的Promise结果，等同于是Promise.resolve(awaitPromise)，因此整体看起来像是Generator和promise的语法糖包装。可以写一个async & await改造的ajax例子：

```js
async function _getData(method,url){
	var a = await ajax(method,url)
	var b = await ajax(method,url,a)  
	console.log('async end')
}
_getData(method,url).then((res)=>{
    //result a 
}).then((res1)=>{
    //result b
}).catch((e)=>{
    //error
})
```

最后解析下上段代码的官方babel：

```js
function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) { 
    try { 
        var info = gen[key](arg); 
        var value = info.value; 
    } catch (error) { 
        reject(error); 
        return;
    } 
    //自执行
    if (info.done) { 
        resolve(value); 
    } else { 
        Promise.resolve(value).then(_next, _throw); 
    } 
}
function _asyncToGenerator(fn) { 
    return function () { 
        var self = this, args = arguments; 
        //用Promise包装
        return new Promise(function (resolve, reject) { 
            var gen = fn.apply(self, args); 
            function _next(value) { 
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value); 
            } 
            function _throw(err) { 
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err); 
            } 
            _next(undefined); 
        }); 
    }; 
}
function _getData() {
    //传入匿名的Generator
  _getData = _asyncToGenerator(function* () {
    yield ajax();
    console.log('async end');
  });
  return _getData.apply(this, arguments);
}
```

*异步机制来源于《JavaScript异步编程》（闹钟书）*

*回调的控制反转来源于《你不知道的JavaScript（中卷）》*

*promise、generator和async\await来源于《ES6标准入门（第三版）》*


